name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: lbianchi-lbl/pse-releng/.github/workflows/pypi.yml@main
    with:
      repository: ${{ github.repository }}
      release-tag: ${{ github.ref_name }}
      pypi-name: idaesplus-release-automation
      test-command: python -c "import idaesplus_release_automation"
