name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  prepublish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - run: echo '${{ toJson(github) }}'
    
  publish:
    needs: [prepublish]
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/pypi.yml
    with:
      repository: ${{ github.repository }}
      release-tag: ${{ github.ref_name }}
      pypi-name: idaesplus-release-automation
      test-pypi-environment: release
      pypi-environment: release
      test-command: python -c "import idaesplus_release_automation"
